Resources:
  TextRegionSelectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/text-region-selector/dist
      Handler: index.handler
      Runtime: nodejs24.x
      Environment:
        Variables:
          NODE_ENV: ${Env:NODE_ENV,prod}
      Events:
        Api:
          Type: Api
          Properties:
            Path: /text-region-selector
            Method: GET

